// Code generated by entc, DO NOT EDIT.

package migrate

import (
	"github.com/facebook/ent/dialect/sql/schema"
	"github.com/facebook/ent/schema/field"
)

var (
	// QccEnterpriseDataColumns holds the columns for the "qcc_enterprise_data" table.
	QccEnterpriseDataColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "name", Type: field.TypeString},
		{Name: "register_status", Type: field.TypeString},
		{Name: "legal_person", Type: field.TypeString},
		{Name: "registered_capital", Type: field.TypeString},
		{Name: "set_up_date", Type: field.TypeString},
		{Name: "verify_date", Type: field.TypeString},
		{Name: "province", Type: field.TypeString},
		{Name: "city", Type: field.TypeString},
		{Name: "county", Type: field.TypeString},
		{Name: "phone", Type: field.TypeString},
		{Name: "other_phones", Type: field.TypeString},
		{Name: "email", Type: field.TypeString},
		{Name: "other_emails", Type: field.TypeString},
		{Name: "unified_social_credit_code", Type: field.TypeString},
		{Name: "taxpayer_identification_number", Type: field.TypeString},
		{Name: "registration_number", Type: field.TypeString},
		{Name: "organization_code", Type: field.TypeString},
		{Name: "insurance_person_nums", Type: field.TypeString},
		{Name: "enterprise_type", Type: field.TypeString},
		{Name: "industry_involved", Type: field.TypeString},
		{Name: "former_name", Type: field.TypeString},
		{Name: "website", Type: field.TypeString},
		{Name: "address", Type: field.TypeString},
		{Name: "business_scope", Type: field.TypeString},
	}
	// QccEnterpriseDataTable holds the schema information for the "qcc_enterprise_data" table.
	QccEnterpriseDataTable = &schema.Table{
		Name:        "qcc_enterprise_data",
		Columns:     QccEnterpriseDataColumns,
		PrimaryKey:  []*schema.Column{QccEnterpriseDataColumns[0]},
		ForeignKeys: []*schema.ForeignKey{},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		QccEnterpriseDataTable,
	}
)

func init() {
}
