// Code generated by entc, DO NOT EDIT.

package qccenterprisedata

const (
	// Label holds the string label denoting the qccenterprisedata type in the database.
	Label = "qcc_enterprise_data"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldRegisterStatus holds the string denoting the register_status field in the database.
	FieldRegisterStatus = "register_status"
	// FieldLegalPerson holds the string denoting the legal_person field in the database.
	FieldLegalPerson = "legal_person"
	// FieldRegisteredCapital holds the string denoting the registered_capital field in the database.
	FieldRegisteredCapital = "registered_capital"
	// FieldSetUpDate holds the string denoting the set_up_date field in the database.
	FieldSetUpDate = "set_up_date"
	// FieldVerifyDate holds the string denoting the verify_date field in the database.
	FieldVerifyDate = "verify_date"
	// FieldProvince holds the string denoting the province field in the database.
	FieldProvince = "province"
	// FieldCity holds the string denoting the city field in the database.
	FieldCity = "city"
	// FieldCounty holds the string denoting the county field in the database.
	FieldCounty = "county"
	// FieldPhone holds the string denoting the phone field in the database.
	FieldPhone = "phone"
	// FieldOtherPhones holds the string denoting the other_phones field in the database.
	FieldOtherPhones = "other_phones"
	// FieldEmail holds the string denoting the email field in the database.
	FieldEmail = "email"
	// FieldOtherEmails holds the string denoting the other_emails field in the database.
	FieldOtherEmails = "other_emails"
	// FieldUnifiedSocialCreditCode holds the string denoting the unified_social_credit_code field in the database.
	FieldUnifiedSocialCreditCode = "unified_social_credit_code"
	// FieldTaxpayerIdentificationNumber holds the string denoting the taxpayer_identification_number field in the database.
	FieldTaxpayerIdentificationNumber = "taxpayer_identification_number"
	// FieldRegistrationNumber holds the string denoting the registration_number field in the database.
	FieldRegistrationNumber = "registration_number"
	// FieldOrganizationCode holds the string denoting the organization_code field in the database.
	FieldOrganizationCode = "organization_code"
	// FieldInsurancePersonNums holds the string denoting the insurance_person_nums field in the database.
	FieldInsurancePersonNums = "insurance_person_nums"
	// FieldEnterpriseType holds the string denoting the enterprise_type field in the database.
	FieldEnterpriseType = "enterprise_type"
	// FieldIndustryInvolved holds the string denoting the industry_involved field in the database.
	FieldIndustryInvolved = "industry_involved"
	// FieldFormerName holds the string denoting the former_name field in the database.
	FieldFormerName = "former_name"
	// FieldWebsite holds the string denoting the website field in the database.
	FieldWebsite = "website"
	// FieldAddress holds the string denoting the address field in the database.
	FieldAddress = "address"
	// FieldBusinessScope holds the string denoting the business_scope field in the database.
	FieldBusinessScope = "business_scope"

	// Table holds the table name of the qccenterprisedata in the database.
	Table = "qcc_enterprise_data"
)

// Columns holds all SQL columns for qccenterprisedata fields.
var Columns = []string{
	FieldID,
	FieldName,
	FieldRegisterStatus,
	FieldLegalPerson,
	FieldRegisteredCapital,
	FieldSetUpDate,
	FieldVerifyDate,
	FieldProvince,
	FieldCity,
	FieldCounty,
	FieldPhone,
	FieldOtherPhones,
	FieldEmail,
	FieldOtherEmails,
	FieldUnifiedSocialCreditCode,
	FieldTaxpayerIdentificationNumber,
	FieldRegistrationNumber,
	FieldOrganizationCode,
	FieldInsurancePersonNums,
	FieldEnterpriseType,
	FieldIndustryInvolved,
	FieldFormerName,
	FieldWebsite,
	FieldAddress,
	FieldBusinessScope,
}
