// Code generated by entc, DO NOT EDIT.

package predicate

import (
	"github.com/facebook/ent/dialect/sql"
)

// QccEnterpriseData is the predicate function for qccenterprisedata builders.
type QccEnterpriseData func(*sql.Selector)
